### ISSUE TITLE
meli up fails on a new machine

### ISSUE THREAD

**Issue by komuW** [komuW/meli#63]
meli -up
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/komuw/meli/api.GetAuth()
	/home/komu/go/src/github.com/komuw/meli/api/auth.go:66 +0x1c8b
main.main()
	/home/komu/go/src/github.com/komuw/meli/main.go:58 +0x531

**Comment by komuW** [comment]
probably has to do with the fact that `~/.docker/config.json` may not exist or may be empty. 

We should fail gracefully and fallback to just using public dockerhub

**Comment by komuW** [comment]
the issue here seems like it is same as; https://github.com/komuW/meli/issues/64 , so closing this one
