### ISSUE TITLE
meli up fails for osx auth

### ISSUE THREAD

**Issue by komuW** [komuW/meli#64]
with an auth file like:
`cat ~/.docker/config.json`
```bash
{
	"auths": {
		"https://index.docker.io/v1/": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/17.09.0-ce (darwin)"
	},
	"credsStore": "osxkeychain"
}
```
we get failure;                     
`meli -up`
```bash
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/komuw/meli/api.GetAuth()
	/home/komu/go/src/github.com/komuw/meli/api/auth.go:66 +0x1c8b
main.main()
	/home/komu/go/src/github.com/komuw/meli/main.go:58 +0x531
```

**Comment by komuW** [comment]
Seems like cred store is the culprit here. It is/was a new-ish thing. 
Look at how docker-compose added support; https://github.com/docker/docker-py/pull/1181/files
